[package]
name = "matching_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = "0.8.1"
crossbeam-channel = "0.5.15"
crossbeam = "0.8.4"
tokio = { version = "1", features = ["full"] }
bytes = "1"

[[bench]]
name = "engine_bench"
harness = false